# opponent_tracker.py
import cv2
import numpy as np

class OpponentTracker:
    """
    Identifies the opponent bot from the environment.
    Can utilize dedicated HSV color tracking, or fallback to targeting the largest generic moving object.
    """
    def __init__(self, enable_hsv_tracking=False, hsv_lower=None, hsv_upper=None, smoothing_alpha=0.4, min_contour_area=500):
        self.enable_hsv_tracking = enable_hsv_tracking
        self.hsv_lower = hsv_lower
        self.hsv_upper = hsv_upper
        self.smoothing_alpha = smoothing_alpha
        self.min_contour_area = min_contour_area

        self.current_center = None
        self.current_bbox = None
        self.smoothed_center = None
        
        print("OpponentTracker: Initialized.")
        if self.enable_hsv_tracking:
            print("OpponentTracker: Using dedicated HSV color tracking.")
        else:
            print("OpponentTracker: Targeting largest moving object.")

    def update(self, frame, hsv_frame, moving_objects, arena_mask=None):
        """
        Identifies the opponent bot's location.
        `moving_objects` is a size-sorted list generated by ArenaTracker.
        Returns (smoothed_center, current_bbox)
        """
        candidate_objects =[]
        
        # Approach 1: Dedicated Color Tracking
        if self.enable_hsv_tracking and self.hsv_lower is not None and self.hsv_upper is not None:
            opponent_mask = cv2.inRange(hsv_frame, self.hsv_lower, self.hsv_upper)
            
            if arena_mask is not None:
                opponent_mask = cv2.bitwise_and(opponent_mask, opponent_mask, mask=arena_mask)

            kernel = np.ones((5, 5), np.uint8)
            opponent_mask = cv2.morphologyEx(opponent_mask, cv2.MORPH_CLOSE, kernel)
            opponent_mask = cv2.morphologyEx(opponent_mask, cv2.MORPH_OPEN, kernel)

            contours, _ = cv2.findContours(opponent_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            
            for cnt in contours:
                area = cv2.contourArea(cnt)
                if area < self.min_contour_area:
                    continue
                
                center = self._contour_center(cnt)
                if center is not None:
                    x, y, w, h = cv2.boundingRect(cnt)
                    candidate_objects.append({'center': center, 'bbox': (x, y, x + w, y + h), 'area': area})
            
            if candidate_objects:
                # Prioritize the largest color-matching object
                candidate_objects.sort(key=lambda x: x['area'], reverse=True)
                self.current_center = candidate_objects[0]['center']
                self.current_bbox = candidate_objects[0]['bbox']
            else:
                self.current_center = None
                self.current_bbox = None

        # Approach 2: Target Largest Moving Object (Fallback)
        else: 
            # Note: moving_objects is already guaranteed to be sorted by size in ArenaTracker, 
            # and our own robot is already filtered out of this list.
            if moving_objects:
                largest_obj = moving_objects[0] 
                self.current_center = largest_obj['center']
                self.current_bbox = largest_obj['bbox']
            else:
                self.current_center = None
                self.current_bbox = None

        # Apply exponential moving average smoothing
        if self.current_center is not None:
            self.smoothed_center = self._smooth(self.smoothed_center, np.array(self.current_center), self.smoothing_alpha)
        
        return (self.smoothed_center, self.current_bbox)

    def draw(self, display_frame):
        """Draws the tracking box around the opponent."""
        if self.current_bbox is not None:
            x1, y1, x2, y2 = self.current_bbox
            cv2.rectangle(display_frame, (x1, y1), (x2, y2), (0, 0, 255), 2) # Blue box

    def _smooth(self, old, new, alpha):
        if old is None:
            return new
        return alpha * new + (1 - alpha) * old

    def _contour_center(self, contour):
        M = cv2.moments(contour)
        if M["m00"] == 0:
            return None
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
        return (cx, cy)